### PR TITLE
Update the traditional chinese translation.

### PR DESCRIPTION
**Pull request by CGLemon**
Update the some translations. But I did not understand the option ```Snappy node switch hack```. Does it means SGF node? What is the effect of the option. Thanks!

### CODE REVIEW

**Comment by rooklift** [comment]
The "Snappy node switch hack" uses an asynchronous (i.e. overlapping communications) method with KataGo which may very slightly reduce perceived lag when changing position while the engine is running. I called it a hack because it makes the communication logic less clean, also the effect is very small.

**Comment by rooklift** [comment]
Thanks!

btw, although GTP is not exactly properly supported, I was wondering if you'd tried it with Sayuri, and whether it works?

**Comment by CGLemon** [comment]
How to load the engine via GTP mode? I could not find the option.

**Comment by rooklift** [comment]
Ah it's available only by directly editing the config.json file.

For example my settings to run Leela are:

```
	"gtp_filepath": "C:\\Programs (self-installed)\\leela-zero\\leelaz.exe",
	"gtp_argslist": [
		"--gtp",
		"--weights",
		"C:\\Programs (self-installed)\\leela-zero\\networks\\0e9ea8.gz"
	]
```

**Comment by CGLemon** [comment]
Thanks, look like that it works well.

Additionally, will you release the document to define the minimal analysis command set? I want to implement the ```kata-analyze``` in order to display the ownermap. But it is hard for me to implement whole  ```kata-analyze``` elements. If Ogatak can define the minimal set, I guess it is very helpful for me and other developers.

**Comment by rooklift** [comment]
Aside from the optional ownership map, it's quite similar to `lz-analyze`, except that things like `winrate`, `lcb`, `prior` (which are in the range 0-10000 in `lz-analyze`) are given in the range `0-1` (as floats) in `kata-analyze`.

**Pull request merged**
