### PR TITLE
Add Simplified Chinese

### PR DESCRIPTION
**Pull request by Bandysol**
Add Simplified Chinese to translations

### CODE REVIEW

**Comment by Bandysol** [comment]
You're welcome!

About first: "open "means" 打开" in Chinese. But if SGF is from the clipboard,I think "粘贴 SGF" is better.

About second: Chinese people's understanding of "backward" seems different from yours. We believe that jumping from 140 steps to 130 steps is called "up" or "forward", and jumping from 130 to 140 is called "down" or "backward".So from the actual effect of this button, it should be called "往前十步".

About third: It's completely possible. But I don't think it's necessary, and if you want to express "costly", you need to write a relatively long sentence.

About fourth: "飘逸" carries this meaning.

Finally: My English is not good, so I translated from the traditional Chinese version, and there may be some grammar errors when replying to you. Please forgive me. Thank you!

**Comment by rooklift** [comment]
About `MENU_ENGINE_PLAYS_POLICY` - this option means KataGo will play using only its raw policy, meaning no search whatsoever. It is much much weaker than normal, but extremely quick.

**Comment by Bandysol** [comment]
It should be much better now

**Comment by rooklift** [comment]
Thank you - if you consider everything finished I'll go ahead and merge it?

**Comment by Bandysol** [comment]
Okay, you can merge at any time

**Comment by rooklift** [comment]
Thank you. If you find anything else that could be improved, feel free to mention it.

**Pull request merged**
