### PR TITLE
Add Menu 'Language' Translation

### PR DESCRIPTION
**Pull request by Bandysol**
Why not?

### CODE REVIEW

**Comment by CGLemon** [comment]
It does not make sense. If a user who doesn't understand the chinese and the default language is chinese,  he is hard to change the language.

**Comment by ParmuzinAlexander** [comment]
I would like to translate this, if someone chooses the wrong language, this is not a problem, the Language menu is always the last right item and in all other programs it is translated. But it a little more difficult, your method does not work.

**Comment by rooklift** [comment]
Sure, that's fine I guess.

**Comment by rooklift** [comment]
btw CGLemon and ParmuzinAlexander - if either of you want to add this item to your translations, you could just tell me here what to write, and save yourself the trouble of a PR, if you like.

**Comment by ParmuzinAlexander** [comment]
I see Failed to verify menupath: {'Language'} it is ok?

**Comment by rooklift** [comment]
Should be fixed now.

**Comment by rooklift** [comment]
I guess the traditional form is 語言 ?

**Pull request merged**
