### PR TITLE
Update the translate.js.

### PR DESCRIPTION
**Pull request by CGLemon**
Fix the issue #62. Hope it will be fine.

### CODE REVIEW

**Comment by rooklift** [comment]
Thanks!

**Comment by rooklift** [comment]
@CGLemon - By the way, since I don't really know about these things I made some enquiries about naming controversies and so on, I was recommended to maybe use the term 繁體中文, would you object to that?

**Comment by CGLemon** [comment]
It's okay. I think they are equal.

**Comment by rooklift** [comment]
OK, I'll do that, thanks.

**Pull request merged**
