### PR TITLE
Update the translations.js.

### PR DESCRIPTION
**Pull request by CGLemon**
I have some questions.

1. What's different between ```MENU_ENGINE_PLAYS_POLICY``` and ```MENU_ENGINE_PLAYS_DRUNK```?
2. Padding is not working well in Chiniese. See the upper of the image. 
 
Screenshot from 2023-04-23 19-59-39

Thanks!

### CODE REVIEW

**Comment by rooklift** [comment]
Yeah I thought it might be best not to translate the info bar at this time. I should probably make it use some sort of table or grid layout so it's always arranged properly. Maybe in future.

The "drunk policy" is a rather poetic name for where KataGo plays policy moves according to their value, so a move with 50% policy has 50% chance to be played, a move with 5% policy has 5% chance, etc etc. This leads to the occasional wild move.

**Comment by CGLemon** [comment]
It's done!

**Comment by rooklift** [comment]
You could leave the info bar stuff in, but commented out, in case I get round to improving the layout...

**Comment by CGLemon** [comment]
Like this?

**Comment by rooklift** [comment]
Exactly, thanks.

**Comment by rooklift** [comment]
By the way, what would you say 飄逸風格 means in English?

**Comment by CGLemon** [comment]
The 飄逸 could be negative meaning or positive meaning. The 飄逸 is negative meaning in here. We say that a player is 飄逸 if he always plays some randomness moves (but not blunder).

The 風格 is style in English.

**Pull request merged**
