### PR TITLE
Update the chinese translation.

### PR DESCRIPTION
**Pull request by CGLemon**
This is not fully chinese translation. Some items are not translated because I have no ideal what is the function doing. Please help me.

1. MENU_STONE_SCORING
What rule does Stone Scoring the use?

2. MENU_PER_MOVE
What's meaning of it?

3. MENU_PREFER_TYGEM_HANDICAP_3_LAYOUT
What's meaning of it?

4. MENU_ESCAPE
What's meaning of it?

5. MENU_ZOBRIST_MISMATCH_CHECKS, MENU_RESET_MISMATCH_WARNINGS
What's meaning of it? What things does the it mismatch?

6. BAD_CONFIG_x
May you give me some examples for all 5 bad config warnings?

### CODE REVIEW

**Comment by rooklift** [comment]
Thanks very much for the efforts!

> MENU_STONE_SCORING
> What rule does Stone Scoring the use?

It's the ruleset where the aim of the game is to get the most stones on the board, so I think it's basically Chinese but with 2-point eye tax per group.

> MENU_PER_MOVE
> What's meaning of it?

It means that, when moving the mouse over the various candidate moves, the ownership map will update giving a (slightly) different ownership map for each.

> MENU_PREFER_TYGEM_HANDICAP_3_LAYOUT
> What's meaning of it?

When setting 3 handicap stones, whether the 3rd stone should be in the top left (the default is bottom right).

> MENU_ESCAPE
> What's meaning of it?

It's mostly there to document that the escape key does something. It can be used to get out of the game info editor, or the About box, or the stderr display (essentially anything that hides the board).

> MENU_ZOBRIST_MISMATCH_CHECKS,
> MENU_RESET_MISMATCH_WARNINGS
> What's meaning of it? What things does the it mismatch?

This is almost entirely for me personally, since it helps me detect bugs. But it checks the hash sent by KataGo for the position against a hash generated by the GUI, to ensure that they're the same. (If they're not the same, it means that the position the GUI thinks KataGo is looking at is not actually what it is looking at.)

> BAD_CONFIG_x
> May you give me some examples for all 5 bad config warnings?

These are actually all the same warning (i.e. they are all displayed at once), it's just that they are split over multiple lines. The point is that the config file is corrupt, but to avoid deleting the user's settings, it will not be written to until the user has corrected or deleted it.

**Comment by CGLemon** [comment]
Thanks. I have already finish it.

I want to check the result on the app but  I do not know js well.  May you give me the document about compiling it?

**Comment by rooklift** [comment]
Thank you.

If you have version 1.6.3, you can find the folder `/resources/app/modules` and replace `translate.js` there.

**Comment by rooklift** [comment]
I'll merge it in. If you want to make minor changes later, you could just open an issue and tell me what needs done. Or make a new pull request if that's more convenient.

Many thanks!

**Comment by rooklift** [comment]
@CGLemon - In 1.6.4 there will be a note in the About box thanking the translators, including "CGLemon", unless you object or want a different name used?

**Comment by rooklift** [comment]
btw, I used Google Translate to look at your translations. Of course one cannot trust Google Translate, but I have a few questions:

Are the "small" and "rectangular" options the right way round?

Google says 背景分析 means "background analysis" - if that's right it's not the intended meaning, which is more like "analysis in the backwards direction (from the end to the start)"

But thank you very much, it looks great.

**Comment by CGLemon** [comment]
Sorry for that. There are some mistakes I missed. I list them all here.

1. MENU_NEW_SMALL_BOARD and MENU_NEW_RECTANGULAR_BOARD are not  right way round.
2. MENU_BACKWARD_ANALYSIS is wrong translation.
3. Need replace the 'Dev' to '開發人員選項'.
4. MENU_WIDE_ROOT_NOISE is not good translation.

Thanks for helping me! I will make a new pull request to fix them.

**Comment by rooklift** [comment]
@CGLemon - if it's simpler for you I can just change the strings.

What would MENU_BACKWARD_ANALYSIS  be?

**Pull request merged**
